name: Build and CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  setup-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (if needed for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install any dependencies (adjust the working-directory if needed)
      - name: Install dependencies
        run: npm install
        working-directory: .github/workflows

      # List files in the repository to verify content
      - name: List files in the current directory
        run: ls -al

      # Create a New Repository on GitHub using MY_PAT token for authentication
      - name: Create a New Repository
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}  # Use MY_PAT as the GitHub token for authentication
        run: |
          NEW_REPO_NAME="new-gh-skeleton"
          RESPONSE=$(curl -s -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               -d "{\"name\":\"$NEW_REPO_NAME\"}" \
               https://api.github.com/user/repos)
          echo "$RESPONSE"
          REPO_URL=$(echo "$RESPONSE" | grep -oP '"clone_url": "\K[^"]+')
          if [ -z "$REPO_URL" ]; then
            echo "Failed to create repository. Exiting..."
            exit 1
          fi
          echo "New repository created: $REPO_URL"
          echo "REPO_URL=$REPO_URL" >> $GITHUB_ENV

      # Run the bump_version.sh script to clone, clean, and push the new repository
      - name: Run bump_version.sh Script
        env:
          MY_PAT: ${{ secrets.MY_PAT }}  # Use MY_PAT token for pushing changes
        run: |
          chmod +x bump_version.sh
          ./bump_version.sh https://github.com/lwersiy/gh-skeleton.git ${{ env.REPO_URL }}

      # Optional: Run additional tests
      - name: Run tests
        run: npm test
        working-directory: .github/workflows
