name: Create Remote Repository and Run bump_version.sh

on:
  workflow_dispatch:

jobs:
  create-repo-and-bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Set up GitHub PAT
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        run: echo "Using GitHub PAT"

      - name: Create a New Remote Repository via GitHub API
        run: |
          NEW_REPO_NAME="new-repo-from-action"
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
               -d "{\"name\":\"$NEW_REPO_NAME\"}" \
               https://api.github.com/user/repos)
          echo "$RESPONSE"
          REPO_URL=$(echo "$RESPONSE" | grep -oP '"clone_url": "\K[^"]+')
          echo "New repository created: $REPO_URL"

      # - name: Verify Repository Creation
      #   run: |
      #     if [ -z "$REPO_URL" ]; then
      #       echo "Failed to create repository. Exiting..."
      #       exit 1
      #     fi
      #     echo "Repository $REPO_URL was successfully created."

      - name: Clone the New Remote Repository
        run: |
          echo "Cloning $REPO_URL..."
          git clone "$REPO_URL"
          cd new-repo-from-action

      - name: Run bump_version.sh Script
        run: |
          chmod +x ./bump_version.sh
          ./bump_version.sh https://github.com/lwersiy/gh-skeleton.git $REPO_URL
